### ISSUE TITLE
[Feature][Dashboard] All Dashboard features implementation follow-up

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/velacp#77]
Feature specification: https://docs.google.com/document/d/1jLOQRP6ffRJl2oo7QIALguKai5A3bH_eHpn9530r094/edit#heading=h.wlc81gyew8l

### 1. Application management
- [ ] create application (workloads/traits auto-rendering) oam-dev/kubevela#680 @majian159 @zzxwill 
  - [x] [Implement API for generating OpenAPI schema for definition](https://github.com/oam-dev/kubevela/pull/784) @zzxwill 
  - [ ] [create application](https://github.com/oam-dev/kubevela/issues/1039) @zzxwill  
    - [ ] [validate inputed parameters of workload/traits by their type](https://github.com/oam-dev/kubevela/issues/740)
    - [ ] Dashboard: Display selected workload type or trait should show in the dropdown oam-dev/kubevela#1069
    - [ ] [Dashboard] "新增" in workload type settings should be in English oam-dev/velacp#76
  - [ ] [Application creation OpenAPI based on new Application object](https://github.com/oam-dev/kubevela/issues/913) @zzxwill 
- [x] list all applications @majian159 @zzxwill 

- [ ] application operations
  - [ ]  [docker logs for application](https://github.com/oam-dev/kubevela/issues/263)

### 2. Capabilities
- Workload  
- [x] list WorkloadDefinitions @sunny0826 @zzxwill 
  - [x] [Add "description" field for each workload from ListWorkloads API](https://github.com/oam-dev/kubevela/pull/824) @zzxwill 
  - [x] [[Dashboard] Refine Dashboard Capabilities: Add descriptions for all workloads as traits](https://github.com/oam-dev/kubevela/discussions/821) @zzxwill 
  - [ ] [[Dashboard] Refine Dashboard Capabilities: `details` could not clearly show all parameters and their type](https://github.com/oam-dev/kubevela/discussions/823) @sunny0826 

- [x] get details of WorkloadDefinition  @sunny0826 

- Trait
- [x] list TraitDefinitions  @sunny0826 @zzxwill 
  - [ ] [[Dashboard] Refine Dashboard Capabilities: add column `title`, `Applies to` and `Operations`](https://github.com/oam-dev/kubevela/discussions/817) @sunny0826 
  - [ ] [[Dashboard] Refine Dashboard Capabilities: unnecessary `apiversion` information](https://github.com/oam-dev/kubevela/discussions/822) @sunny0826 
- [x] get TraitDefinition   @sunny0826 

### 3. Logo and appearance
- [ ] [Dashboard]update logo oam-dev/kubevela#1043
