### ISSUE TITLE
Umbrella features for KubeVela Dashboard

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/velacp#79]
# Application
### detail
- [ ] provide application logs function to see logs of pods oam-dev/kubevela#263
- [ ] provide application exec function to login a container oam-dev/kubevela#264

### create
- [x] refine creation UX @hanxie-crypto 

### Component
- [x] design and implement components operations
- [ ] [API] implement component operations related API
    - [x] api for `vela comp run` oam-dev/kubevela#271 
    - [x] api for `vela comp ls` oam-dev/kubevela#272
    - [x] api for `vela comp show` oam-dev/kubevela#273
    - [ ] api for `vela comp status` oam-dev/kubevela#274 
    - [x] api for `vela comp delete` oam-dev/kubevela#275 

### Workloads/Traits
- [ ] [API] List more parameters and catalog them for core workloads and traits oam-dev/kubevela#265 @zzxwill
